### ISSUE TITLE
The Ring of Seven Curses blocks any damage.

### ISSUE THREAD

**Issue by KeroBetick** [Extegral/Enigmatic-Legacy#425] opened 2023-06-20 10:04 UTC
#### Versions:
 * Enigmatic Legacy 1.18.2 2.25.0:
 * Curios API 1.18.2 5.0.9.0:
 * Patchouli 1.18.2 71.1:
 * Forge: 40.2.4
 * Server software: Magma Foundation c1568e15

#### Description of a Bug:
With the ring on, and at least three pieces of armor(even leather armor) with Protection 4 on, the damage does not pass at all. This only happens on the server. I checked in a single-player game and everything is fine there, the damage passes correctly.

#### How to Reproduce:
1. Wear Ring of Seven Curses
2. Wear any armor
3. Try damage from any source
4. The number of hearts will decrease

#### Logs:
[latest(1).log](https://github.com/Aizistral-Studios/Enigmatic-Legacy/files/11798665/latest.1.log)
[debug.log](https://github.com/Aizistral-Studios/Enigmatic-Legacy/files/11798667/debug.log)

**Comment by Aizistral** [comment] 2023-08-03 11:13
It is likely Enigmatic Legacy is not at fault here. Similar issue happened in the past with Blue Skies and Project MMO (#289), and the real issue was caused by those mods, even though it was Enigmatic Legacy's item that triggered it.

**Comment by Aizistral** [comment] 2023-08-03 11:59
Since this is reported for 1.18.2 and I don't intend to release any further 1.18 updates, I'll be closing this. Feel free to re-open if you encounter such an issue on newer versions.

**Closed as not planned by Aizistral** 2023-08-03 11:59 UTC
Labels: bug, irreproducible
