### ISSUE TITLE
Crash on startup 1.18.2

### ISSUE THREAD

**Issue by keepinitreal247** [Extegral/Enigmatic-Legacy#319] opened 2022-05-08 04:10 UTC
#### Notice
The Mod seems to work fine on its own but when I put other mods with it crashes I don't know which mods are conflicting with it either so that's why the debug has other mods included

#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: [EnigmaticLegacy-2.21.1.jar]
 * Curios API: curios-forge-1.18.2-5.0.7.0.jar
 * Patchouli: Patchouli-1.18.2-67.jar
 * Forge: forge-1.18.2-40.1.0-installer.jar

#### Description of a Bug:
A clear and concise description of what the issue is.

#### How to Reproduce:
1. Put enigmatic legacy in with its requirements
2. Open Minecraft
3. Press Play
4. Behold!

Debug Log: https://gist.github.com/keepinitreal247/2e55ce5ef5df86e0a91040f8d0b74e05

**Comment by Aizistral** [comment] 2022-05-08 12:43
Duplicate of #320.

**Closed as completed by Aizistral** 2022-05-08 12:43 UTC
Labels: bug, duplicate, crash
