### ISSUE TITLE
"Ambience - Extras" mod by viniciusgf1 presumably injecting unnamed LootPool (relates to issue #132)

### ISSUE THREAD

**Issue by Quacksalber99** [Extegral/Enigmatic-Legacy#150] opened 2021-02-10 21:16 UTC
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: v2.10.3
 * Curios API: 1.16.5-4.0.4.0
 * Patchouli: 1.16.4-48
 * Forge: 1.16.5-36.0.21

#### Description of a Bug:
After a few hours of searching what might cause some chests in my world to spawn empty i stumbled upon issue #132, and after installing enigmatic legacy my game did indeed crash after world loadup, resulting in the latest.log found further down (be warned, my current modded 1.16.5 build might be poorly optimized). After reading what i could understand from the log, i suspected the mod "Ambience - Extras" by viniciusgf1 (https://www.curseforge.com/minecraft/mc-mods/ambience-extras) as the potential cause for this, and removing the mod did indeed result in no crash on world loadup. My poor knowledge of code is probably not sufficient to explain the issue correctly to the mod author, so im posting this here instead.

#### How to Reproduce:
1. install Ambience-1.16.4-1.0.1
2. install Enigmatic Legacy v2.10.3
3. create a new world
4. crash time!

#### Logs:
latest.log of crash with full build: https://textbin.net/ZmrTsIDiNt
latest.log of reproduced crash with reduced number of mods (considerably shorter) : https://pastebin.com/Gy13Zezw

**Comment by Aizistral** [comment] 2021-02-10 23:30
Oh, finally someone making a proper report on such case. I was desperate by now that I shall never witness this day coming.

You have deduced correctly that the problem is on the side of **Ambience - Extras**. I have thus reported it to their repository: https://github.com/viniciusgf2/Ambience/issues/67

**Comment by Aizistral** [comment] 2021-03-12 13:35
Closing this as it lost revelance due to issue with unnamed loot pools being fixed on the side of Forge.

**Closed as completed by Aizistral** 2021-03-12 13:35 UTC
Labels: bug, 3rd party issue, status: confirmed
