### ISSUE TITLE
incompatibility with hunterillager 1.16.4. 1.2.2 mod

### ISSUE THREAD

**Issue by wardaddy456** [Extegral/Enigmatic-Legacy#168] opened 2021-03-27 14:02 UTC
[latest.log](https://github.com/Aizistral-Studios/Enigmatic-Legacy/files/6215789/latest.log)

#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.11.2
 * Curios API: 1.16.4.-4.0.3.5
 * Patchouli: 1.16.4-50
 * Forge: 35.1.4
 * hunterillager: 1.16.4-1.2.2

#### Description of a Bug:
A clear and concise description of what the issue is.

when all above installed, the game will not start.

#### How to Reproduce:
1. ... install all of listed above (enigmatic, forge, curios api, patchouli, hunterillager)
2. ... try to run the game, it wont start
3. ...
4. Behold!

#### Logs:

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by Aizistral** [comment] 2021-03-27 16:11
Duplicate of #115. Great to see they still haven't fixed that damn mixin on their side. I once had myself written an issue on this to Hunter Illager repository here on github, though that repository seems to be concealed from public now for some reason.

**Closed as completed by Aizistral** 2021-03-27 16:11 UTC
Labels: bug, duplicate
