### ISSUE TITLE
[1.16.5] Worn curios items are unequipping on reload/relog...

### ISSUE THREAD

**Issue by Jusey1** [Extegral/Enigmatic-Legacy#162] opened 2021-03-17 18:16 UTC
#### Versions:
 * Enigmatic Legacy: 2.11.2
 * Curios API: 4.0.5.0
 * Patchouli: 50.0.0
 * Forge: 36.1.0

#### Description of a Bug:
So, um. 2.11.2 was suppose to fix this bug but it didn't. Essentially, any worn curios items will still be ejected into the player's inventory upon logging back into the world (be it singleplayer or server. Tested on both sides).

#### How to Reproduce:
1. Equip items.
2. Leave.
3. Load world / log onto server.
4. Behold!

#### Logs:

Crash Log: N/A.

**Comment by Aizistral** [comment] 2021-03-17 18:20
No goddamn way!

**Comment by Aizistral** [comment] 2021-03-17 18:36
I have tested this with the exact same Forge/Curios/Enigmatic Legacy versions as you specified and could not reproduce. Are you certain there are no other mods involved in this?

**Comment by 2el222** [comment] 2021-03-17 19:21
Still happening to me too, did u try to add custom slots for curio? i have them added in my server, too lazy to test

**Comment by 2el222** [comment] 2021-03-17 19:22
and jusey could u give me ur mod list. maybe its a mod thats causing this and we can find out

**Comment by Jusey1** [comment] 2021-03-17 19:38
I figured it out. Endergetic 3.0.0 is causing the issue. The moment I added that mod back into my instance, I get this bug back.

**Comment by 2el222** [comment] 2021-03-17 19:43
Well I dont have Endergetic and it is still happening :)

**Comment by Jusey1** [comment] 2021-03-17 20:15
Well Endergetic is doing it for me. So, no idea what is going on here.

**Comment by 2el222** [comment] 2021-03-17 23:01
Abnormals core on itself doesn't cause it, but if u add any mod that's dependant on it, in my case Upgraded Aquatic and Autumnity, it starts to happen

**Comment by Jusey1** [comment] 2021-03-18 14:43
Those two mods aren't causing it for me, just Endergetic Expansion. Odd.

**Comment by Jusey1** [comment] 2021-03-18 16:29
Okay, I just learn that scrolls are being ejected for me but not rings and spellstones... Maybe each Adnormal mod is ejecting different items? Wait. It's not scrolls being ejected. It's cursed items in general instead of all items.

**Comment by SenCarryr** [comment] 2021-03-19 21:53
Having a similar issue with current version, except mine is duping instead of unequipping

**Comment by Aizistral** [comment] 2021-04-14 13:20
I guess this is no more than a duplicate of #159 now.

**Closed as completed by Aizistral** 2021-04-14 13:20 UTC
Labels: bug, duplicate, 3rd party issue, status: confirmed
