### ISSUE TITLE
Ceaseless enchantment breaks Sharpshooter enchantment

### ISSUE THREAD

**Issue by Creeperseatfood** [Extegral/Enigmatic-Legacy#191] opened 2021-06-30 02:30 UTC
I have a very strange problem, I am on 1.16.5 enigmatic legacy 2.11.4 and spartan weaponry 2.1.0 beta-4. I had a diamond strengthened crossbow enchanted with many enchantments including sharpshooter, quick charge, ect. It worked perfectly with the bolts. I later enchanted it with ceaseless, this broke the sharpshooter enchantment. Now any crossbow with sharpshooter acts if it uses ceaseless without ceaseless. I can't shoot bolts while using sharpshooter anymore even though I previously could. I tried using commands to remove the ceaseless and that was how I figured out that it somehow got bound to the sharpshooter enchantment. This is a really strange bug and it ruined my crossbow build of Sharpshooter V, Quick Charge III, and Unbreaking III. I tried remaking more crossbows with the enchantments fresh from the enchantment table and /or enchanted books and the bug happens 100% of the time with the sharpshooter enchantment. Summary: Ceaseless enchantment permanently broke the Sharpshooter enchantment... at least in that world.

**Comment by Creeperseatfood** [comment] 2021-06-30 02:32
This person appears to have a very similar issue.
https://github.com/Aizistral-Studios/Enigmatic-Legacy/issues/124

**Comment by Creeperseatfood** [comment] 2021-07-01 02:27
This person appears to have a similar issue:
https://github.com/Aizistral-Studios/Enigmatic-Legacy/issues/124

**Comment by Aizistral** [comment] 2021-07-05 07:41
So, is your issue in fact the same as #124? Your description of the bug is just really confusing, and I don't really get whether you have issues with Ceaseless, Sharpshooter, crossbows from Spartan Weaponry, or whatever specific combination of those. I also don't get what exactly this bug makes happen in your instance.

**Comment by Creeperseatfood** [comment] 2021-07-05 14:07
Yes, the first two paragraphs in "Description of a Bug:" https://github.com/Aizistral-Studios/Enigmatic-Legacy/issues/124 . The reproduction method is the same, enchanting with ceaseless and sharpshooter on the diamond strengthened crossbow.

**Comment by Jusey1** [comment] 2021-07-05 16:53
This looks like it could be an issue with Spartan Weaponry specifically? Due to how Ceaseless works, it just doesn't like Spartan Weaponry's crossbows at all, which could be causing the world to get broken like this.

**Comment by Aizistral** [comment] 2021-07-05 17:08
No, it's honestly just a badly written implementation behind crossbow enchantments on my side. At that time I still attempted to avoid diving into Mixin, so it was only possible to make these enchantments work by duplicating a lot of code in a way that is practically guaranteed to break with custom crossbows.

I'll close this as duplicate of #124 then.

**Closed as completed by Aizistral** 2021-07-05 17:08 UTC
Labels: bug, duplicate, 3rd party issue
