### ISSUE TITLE
Can't see the iventory part, where you Equip rings etc.

### ISSUE THREAD

**Issue by ViggoHub** [Extegral/Enigmatic-Legacy#169] opened 2021-03-28 15:33 UTC
Hello.

I recently started a new play through, with this mod on, and when i first started everything worked fine. The all of a sudden, i can't Equip or unequip the rings ect. Because i can't see the menu where you do it. 

Hope somebody can help:)

**Comment by alpharou** [comment] 2021-03-28 19:27
I guess you're talking about the Curios inventory. It's by default accesed with keybind G:
![image](https://user-images.githubusercontent.com/8113318/112765163-351c8180-900c-11eb-8cd3-d54d542e9a32.png)

You can also access it by clicking the little spiked square besides your character:
![image](https://user-images.githubusercontent.com/8113318/112765202-541b1380-900c-11eb-834c-a879997e87b4.png)

**Comment by Aizistral** [comment] 2021-04-01 12:17
If you're unable to locate where Curios inventory is - that's not a bug report. You should've made an issue from question template or used discussions for that.

Also, @alpharou seems to already have conveniently pointed out where you should look for that inventory. Closing this then.

**Closed as completed by Aizistral** 2021-04-01 12:17 UTC
Labels: bug, invalid
