### ISSUE TITLE
[README] Oh no, my world crashes when loading with Enigmatic Legacy v2.10.3+!

### ISSUE THREAD

**Issue by Aizistral** [Extegral/Enigmatic-Legacy#132] opened 2021-01-09 15:47 UTC
What you likely encountered is caused by handler that purposefully crashes the world upon loading if any mod in your modpack attempts to inject unnamed `LootPool` to any loot table - that is, without calling `LootPool.Builder#name(String)` and setting that name to something other than `null` before injection. This feature was implemented in version **2.10.3** of **Enigmatic Legacy**, and will persist unchanged for some time until I can give it a better implementation.

# Why the hell you've done it?
Because injection of unnamed `LootPool` leads to an error state later if any other mod attempts to manipulate that loot table, which in turn causes no loot to generate from it.

It is a commonly known issue among mod developers and is incredibly frustrating to deal with for us, modpack developers and for regular users alike, since looking at log files doesn't allow to figure out what mod is responsible for injection. Furthermore, a lot of people do not notice, or for some arcane reason do not care to report subsequent issues with loot after noticing it.

## And how does crashing the whole thing help?
Well, first things first, it's possible you have noticed whole thing crashing and arrived here to report it, right? In such case, my feature already done half of it's job - brought you and your little crashlog all the way over to this repository. Now, it would be nice of you to paste that crashlog somewhere, and create a bug report describing what you encountered and providing a link to crashlog you've just pasted. Extra points if you link your `latest.log` file instead, since it might contain more information. Apparently, in this instance you don't have to reproduce your issue without other mods first like default bug report template kindly asks you.

You see, the deal is that **Enigmatic Legacy** gathers information about invalid pool injection during the world loading, and only crashes the whole thing once that loading is over and at least one such injection was indicated. This happening is preceeded by first printing out collected stacktraces to log file. Those stacktraces should contain event handlers responsible for injections, therefore allowing to figure out what exact mods are to blame and where is their faulty code. Now all we need is to get someone who actually knows how to read those stacktraces, for instance - me, to check them out and report what and where needs to be fixed to respective mod developers. You can also do it yourself if you feel like and know how.

## How about I don't want to participate in your debugging program any longer?
Proceed to your `config` folder within Minecraft installation directory, find file named `enigmaticlegacy-common.omniconf` there, and open it with the text editor of your choice. Scroll down until you find this little option within **Accesibility Config** category:

![image](https://user-images.githubusercontent.com/47505981/104095952-fba06980-5299-11eb-8323-843f5b7180a2.png)

See that `B:CrashOnUnnamedPool=true` thing? Change it to be `B:CrashOnUnnamedPool=false` thing. Then save your file and close the editor. Now your game won't be crashing, and you can enjoy all the screwed up loot tables as much as you want.

## What mods are already known for this bug?
Well, here's the full list of mods that we so far managed to find out as being responsible for unnamed `LootPool` injections ever since I implemented this handler. I will try to keep this list updated in the future, so you can avoid creating duplicate bugreports by first checking if you use any of them with versions specified:
* ~~**Wyrmroost**, version 1.2.10 and prior (MC 1.16.x). Reported: https://github.com/WolfShotz/Wyrmroost/issues/203~~ Fixed as of version **1.2.11**
* **ForageCraft**, version 2.1.2 and prior (MC 1.16.x). Reported: https://github.com/Jonathing/ForageCraft/issues/75
* ~~**Spartan Weaponry**, version 2.1.0-beta-1 and prior (MC 1.16.x). Reported: [ObviousSpartan/SpartanWeaponry#161](https://www.curseforge.com/minecraft/mc-mods/spartan-weaponry/issues/161)~~ Fixed as of version **2.1.0-beta-2**
* ~~**Repurpose**, version 1.4.0.0 and prior (MC 1.16.x). Reported: https://github.com/Brian-Wuest/MC-Repurpose/issues/34~~ Fixed as of version **1.4.0.1**
* **Chance Cubes**, version 5.0.2.394 and prior (MC 1.16.x). Reported: https://github.com/TheTurkeyDev/ChanceCubes/issues/225
* ~~**MCJD**, version 2.1 and prior (MC 1.16.x). Reported: https://github.com/Shoxie12/MCDJ/issues/13~~ Fixed as of version **2.1.1**
* **Ropes Mod**, version 1.1.0 and prior (MC 1.16.x). Reported: https://github.com/TheGoldCrayon/RopesMod/issues/8
* **Ambience - Extras**, version 1.0.1 (MC 1.16.x). Reported: https://github.com/viniciusgf2/Ambience/issues/67

**Comment by Pfidget** [comment] 2021-01-09 22:18
I have a crash on my current world, this is the crash log that was generated :  https://pastebin.com/4qMx8zS2  I think the problem is with repurpose mod but I'm not experienced with reading these crash logs or fixing the issues.

**Comment by Aizistral** [comment] 2021-01-09 22:58
> I have a crash on my current world, this is the crash log that was generated : https://pastebin.com/4qMx8zS2 I think the problem is with repurpose mod but I'm not experienced with reading these crash logs or fixing the issues.

Yes, the stacktrace points to Repurpose. I have reported an issue to them: https://github.com/Brian-Wuest/MC-Repurpose/issues/34

However, to you and anyone else reading this in future, I strongly suggest to avoid posting crashlog within comments of this issue. Make your own one, the "**New issue**" button is not that difficult to locate: 

![image](https://user-images.githubusercontent.com/47505981/104110271-78e9cf80-52d6-11eb-8d67-17cab6161df3.png)

**Comment by noobanidus** [comment] 2021-01-17 23:03
I've [created a PR for Forge to hopefully fix their issue](https://github.com/MinecraftForge/MinecraftForge/pull/7605) as it is their issue.

**Comment by Aizistral** [comment] 2021-01-19 12:12
> I've [created a PR for Forge to hopefully fix their issue](https://github.com/MinecraftForge/MinecraftForge/pull/7605) as it is their issue.

I really wanted to comment on that request, but I discovered myself being banned from MinecraftForge repositories, for reason that I only learned today and still cannot percieve as other than absolutely ridiculous: https://forums.minecraftforge.net/topic/96534-cannot-interact-with-minecraftforge-repositories/?tab=comments#comment-439654

For reference, here's the piece of code I linked in that thread: https://github.com/Extegral/Enigmatic-Legacy/blob/26a625317eff40fae395acfcc996051784146f57/src/main/java/com/integral/enigmaticlegacy/mixin/MixinForgeHooks.java#L26

**Comment by MWall541** [comment] 2021-01-19 19:16
I have pushed an update for Wyrmroost that has this fix in place.
Can be found on curseforge here: https://www.curseforge.com/minecraft/mc-mods/wyrmroost/files/3173775

**Comment by Aizistral** [comment] 2021-01-23 16:00
> I have pushed an update for Wyrmroost that has this fix in place.
> Can be found on curseforge here: https://www.curseforge.com/minecraft/mc-mods/wyrmroost/files/3173775

Alright, I updated the list of problematic mods to indicate what mods have fixed the issue on their side so far.

**Comment by steveper68** [comment] 2021-01-25 08:56
This is the crashlog I got when trying to generate a world:
https://pastebin.com/g83rHSKD

**Comment by Aizistral** [comment] 2021-01-25 14:21
Dammit @steveper68, this was just above:

![image](https://user-images.githubusercontent.com/47505981/105717603-9f3b7c00-5f20-11eb-9c73-bb9a10ad445e.png)

Could you please be so kind and actually follow my tip. I suppose after months of work I have put into this mod I at least deserve five more minutes of that time you'll have to spend to create bug report and properly fill in all the data requested, especially since in this instance you don't have to reproduce your issue without other mods first like default bug report template kindly asks you.

**Comment by steveper68** [comment] 2021-01-25 18:24
> Dammit @steveper68, this was just above:
> 
> ![image](https://user-images.githubusercontent.com/47505981/105717603-9f3b7c00-5f20-11eb-9c73-bb9a10ad445e.png)
> 
> Could you please be so kind and actually follow my tip. I suppose after months of work I have put into this mod I at least deserve five more minutes of that time you'll have to spend to create bug report and properly fill in all the data requested, especially since in this instance you don't have to reproduce your issue without other mods first like default bug report template kindly asks you.

Hey, I'm actually really sorry, I should've been more careful. It's my first time posting something on github, I created an account just for this. I saw that you replied to a guy that posted his crashlog in a comment above so I thought "Maybe they want it posted here". If anything like this happens again I'm definitely going to create a bug report.

**Comment by Aizistral** [comment] 2021-01-25 18:39
> Hey, I'm actually really sorry, I should've been more careful. It's my first time posting something on github, I created an account just for this. I saw that you replied to a guy that posted his crashlog in a comment above so I thought "Maybe they want it posted here". If anything like this happens again I'm definitely going to create a bug report.

Alright, whatever. Anyways, stacktrace in your log points to mod called MCDJ. I have already reported an issue to them: https://github.com/Shoxie12/MCDJ/issues/13

**Comment by PedroCabanasRumayor** [comment] 2021-02-07 02:20
This is my server error report. I dont know how to show the lastest.log. Hope that helps
https://mclo.gs/u9ewCw7

**Comment by Aizistral** [comment] 2021-02-09 15:47
> This is my server error report. I dont know how to show the lastest.log. Hope that helps
> https://mclo.gs/u9ewCw7

`latest.log` only exists on client, in case of running a dedicated server the file you provided is what needed. However, there is nothing in the log that would be related to Enigmatic Legacy, and error seems to be caused by other mod entirely, the one bearing the name SimplePlanesMod. Report it to that mod's developer.

Also I once again advise to not report crashes you get with Enigmatic Legacy in this issue, whether they are related to what it's dedicated to or not. Seriosly guys, just make your own one, it's NOT THAT COMPLICATED.

**Comment by noobanidus** [comment] 2021-02-09 21:57
[The forge PR was merged](https://github.com/MinecraftForge/MinecraftForge/pull/7605)! Unfortunately that only helps when people are fully updated, but still.

**Closed as completed** 2021-03-12 13:33 UTC

**Comment by Aizistral** [comment] 2021-03-12 13:35
Closing this as it lost revelance due to issue with unnamed loot pools being fixed on the side of Forge.
