### ISSUE TITLE
Issue with loading the Acknowledgement's pages

### ISSUE THREAD

**Issue by Ahcknus** [Extegral/Enigmatic-Legacy#331] opened 2022-05-23 22:15 UTC
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.2.1 (For minecraft 1.16)
 * Curios API: 1.16.1-3.0.0.2
 * Patchouli: 1.16-39
 * Forge: 1.16.1

#### Description of a Bug:
A clear and concise description of what the issue is.

The pages of the item "The Acknowledgement" have no content in them. Patchouli seems to have an issue loading them (I have redownloaded a fresh copy of both Patchouli and EnigmaticLegacy.
#### How to Reproduce:
1. ...
2. ...
3. ...
4. Behold!

#### Logs:

[2022-05-23-7.log](https://github.com/Aizistral-Studios/Enigmatic-Legacy/files/8758340/2022-05-23-7.log)

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by Aizistral** [comment] 2022-05-23 22:18
Wait, why are you on 1.16.1? Enigmatic Legacy 2.11.12 lists 1.16.3 as the lower bound of compatibility.

**Comment by Aizistral** [comment] 2022-05-23 22:19
Oh wait you're not even using 2.11.12. God those old versions...

**Comment by Ahcknus** [comment] 2022-05-23 22:19
I am using a modpack rn to host a server for some friends and myself and the modpack is on version 1.16.1 for miencraft

**Comment by Ahcknus** [comment] 2022-05-23 22:20
If it really is just because of how the mod version I am using is old, Ill just resort to watching a bunch of videos to replace using the book lol

**Comment by Aizistral** [comment] 2022-05-23 22:21
Wait, I need to check what version of Patchouli EL 2.2.1 was built against.

**Comment by Aizistral** [comment] 2022-05-23 22:26
It should have been 1.16-39, the exact version you are using. Very weird indeed. I will wait for @StygianNights to independently reproduce this with versions listed.

**Comment by StygianNights** [comment] 2022-05-24 00:28
~~Without the rest of the pack I know you are using, Filmpack, the versions in question are operating as expected. Going to test filmpack now.~~

~~edit1: May have found why I didn't see an issue, please hold.~~
Nope, there is an issue only present in Filmpack, not the 3 mods in particular mentioned in this issue report.

**Comment by StygianNights** [comment] 2022-05-24 01:00
So from a bit of testing, The mods listed above work fine and show the articles in the acknowledgement with no issues whatsoever, But the moment they are in the modpack "Filmpack", the Haste Potion page in particular has an issue, which I am guessing is causing the whole of the book to stop functioning as intended. 

This makes me think a potion recipe is causing issues somehow, that or it's some kind of weird localization issue, though why I do not know. 
Lines that leave me to believe all this in logs: 
<details>
<summary>Log File Spam</summary>

> [17:51:51] [main/INFO]: [CHAT] New version of �6Enigmatic Legacy�5 was established: 2.11.12 Release. You must behold it's greatness!
> [17:51:51] [main/INFO]: Loaded 694 advancements
> [17:51:51] [main/ERROR]: Error while loading contents for book enigmaticlegacy:the_acknowledgment
> java.lang.RuntimeException: Error building entry enigmaticlegacy:brewing/haste_potion
> 	at vazkii.patchouli.client.book.BookContents.lambda$reload$5(BookContents.java:141) ~[?:1.16-39]
> 	at vazkii.patchouli.client.book.BookContents$$Lambda$12948/622701827.accept(Unknown Source) ~[?:?]
> 	at java.util.HashMap$Values.forEach(HashMap.java:972) ~[?:1.8.0_51]
> 	at vazkii.patchouli.client.book.BookContents.reload(BookContents.java:137) [?:1.16-39]
> 	at vazkii.patchouli.common.book.Book.reloadContents(Book.java:186) [?:1.16-39]
> 	at vazkii.patchouli.common.book.BookRegistry$$Lambda$12937/368230318.accept(Unknown Source) [?:1.16-39]
> 	at java.util.HashMap$Values.forEach(HashMap.java:972) [?:1.8.0_51]
> 	at vazkii.patchouli.common.book.BookRegistry.reloadContents(BookRegistry.java:105) [?:1.16-39]
> 	at vazkii.patchouli.client.book.ClientBookRegistry.reload(ClientBookRegistry.java:63) [?:1.16-39]
> 	at vazkii.patchouli.client.base.ClientAdvancements.onClientPacket(ClientAdvancements.java:40) [?:1.16-39]
> 	at net.minecraft.client.multiplayer.ClientAdvancementManager.func_192799_a(SourceFile:57) [?:?]
> 	at net.minecraft.client.network.play.ClientPlayNetHandler.func_191981_a(ClientPlayNetHandler.java:1305) [?:?]
> 	at net.minecraft.network.play.server.SAdvancementInfoPacket.func_148833_a(SourceFile:37) [?:?]
> 	at net.minecraft.network.play.server.SAdvancementInfoPacket.func_148833_a(SourceFile:16) [?:?]
> 	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) [?:?]
> 	at net.minecraft.network.PacketThreadUtil$$Lambda$12409/72497691.run(Unknown Source) [?:?]
> 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
> 	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
> 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
> 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?]
> 	at jeresources.util.LootTableHelper.getManager(LootTableHelper.java:173) [?:0.11.1.93]
> 	at jeresources.compatibility.minecraft.MinecraftCompat.registerVanillaMobs(MinecraftCompat.java:51) [?:0.11.1.93]
> 	at jeresources.compatibility.minecraft.MinecraftCompat.init(MinecraftCompat.java:35) [?:0.11.1.93]
> 	at jeresources.compatibility.Compatibility.init(Compatibility.java:26) [?:0.11.1.93]
> 	at jeresources.proxy.CommonProxy.initCompatibility(CommonProxy.java:14) [?:0.11.1.93]
> 	at jeresources.jei.JEIConfig.registerCategories(JEIConfig.java:71) [?:0.11.1.93]
> 	at mezz.jei.load.PluginLoader.lambda$new$2(PluginLoader.java:110) [?:7.0.1.10]
> 	at mezz.jei.load.PluginLoader$$Lambda$12886/2125068136.accept(Unknown Source) [?:7.0.1.10]
> 	at mezz.jei.load.PluginCaller.callOnPlugins(PluginCaller.java:26) [?:7.0.1.10]
> 	at mezz.jei.load.PluginLoader.<init>(PluginLoader.java:110) [?:7.0.1.10]
> 	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:69) [?:7.0.1.10]
> 	at mezz.jei.startup.ClientLifecycleHandler.onRecipesLoaded(ClientLifecycleHandler.java:127) [?:7.0.1.10]
> 	at mezz.jei.startup.ClientLifecycleHandler.lambda$new$2(ClientLifecycleHandler.java:104) [?:7.0.1.10]
> 	at mezz.jei.startup.ClientLifecycleHandler$$Lambda$11823/1284133013.accept(Unknown Source) [?:7.0.1.10]
> 	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) [eventbus-3.0.3-service.jar:?]
> 	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) [eventbus-3.0.3-service.jar:?]
> 	at net.minecraftforge.eventbus.EventBus$$Lambda$2777/1619759213.invoke(Unknown Source) [eventbus-3.0.3-service.jar:?]
> 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) [eventbus-3.0.3-service.jar:?]
> 	at net.minecraftforge.client.ForgeHooksClient.onRecipesUpdated(ForgeHooksClient.java:727) [?:?]
> 	at net.minecraft.client.network.play.ClientPlayNetHandler.func_199525_a(ClientPlayNetHandler.java:1344) [?:?]
> 	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:27) [?:?]
> 	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:15) [?:?]
> 	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) [?:?]
> 	at net.minecraft.network.PacketThreadUtil$$Lambda$12409/72497691.run(Unknown Source) [?:?]
> 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
> 	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
> 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
> 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?]
> 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:922) [?:?]
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:582) [?:?]
> 	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
> 	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
> 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.1-32.0.108.jar:32.0]
> 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$477/471835796.call(Unknown Source) [forge-1.16.1-32.0.108.jar:32.0]
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-6.1.1.jar:?]
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-6.1.1.jar:?]
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?]
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?]
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?]
> Caused by: java.lang.RuntimeException: Error while loading entry enigmaticlegacy:brewing/haste_potion page 1
> 	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:224) ~[?:1.16-39]
> 	at vazkii.patchouli.client.book.BookContents.lambda$reload$5(BookContents.java:139) ~[?:1.16-39]
> 	... 61 more
> Caused by: java.lang.RuntimeException: Error setting up template processor
> 	at vazkii.patchouli.client.book.template.BookTemplate.compile(BookTemplate.java:94) ~[?:1.16-39]
> 	at vazkii.patchouli.client.book.page.PageTemplate.build(PageTemplate.java:23) ~[?:1.16-39]
> 	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:221) ~[?:1.16-39]
> 	at vazkii.patchouli.client.book.BookContents.lambda$reload$5(BookContents.java:139) ~[?:1.16-39]
> 	... 61 more
> Caused by: java.lang.NullPointerException
> 	at com.integral.enigmaticlegacy.handlers.AdvancedBrewingRecipeProcessor.setup(AdvancedBrewingRecipeProcessor.java:53) ~[?:2.0]
> 	at vazkii.patchouli.client.book.template.BookTemplate.compile(BookTemplate.java:92) ~[?:1.16-39]
> 	at vazkii.patchouli.client.book.page.PageTemplate.build(PageTemplate.java:23) ~[?:1.16-39]
> 	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:221) ~[?:1.16-39]
> 	at vazkii.patchouli.client.book.BookContents.lambda$reload$5(BookContents.java:139) ~[?:1.16-39]
> 	... 61 more
> [17:51:52] [main/WARN]: Queried for unknown config flag: mod:gardenofglass
> [17:51:52] [main/WARN]: Queried for unknown config flag: mod:gardenofglass
> [17:51:52] [main/WARN]: Queried for unknown config flag: mod:gardenofglass
> [17:51:52] [main/WARN]: Queried for unknown config flag: mod:gardenofglass
> [17:51:52] [main/WARN]: Queried for unknown config flag: mod:gardenofglass
> [17:51:52] [main/WARN]: You're trying to deserialize an object of type interface net.minecraft.util.text.ITextComponent from one of type class net.minecraft.util.text.TranslationTextComponent. This is likely not what you want!
> [17:51:52] [main/WARN]: You're trying to deserialize an object of type interface net.minecraft.util.text.ITextComponent from one of type class net.minecraft.util.text.TranslationTextComponent. This is likely not what you want!
> [17:51:52] [main/WARN]: You're trying to deserialize an object of type interface net.minecraft.util.text.ITextComponent from one of type class net.minecraft.util.text.TranslationTextComponent. This is likely not what you want!
> [17:51:52] [main/WARN]: You're trying to deserialize an object of type interface net.minecraft.util.text.ITextComponent from one of type class net.minecraft.util.text.TranslationTextComponent. This is likely not what you want!
> [17:51:52] [main/WARN]: You're trying to deserialize an object of type interface net.minecraft.util.text.ITextComponent from one of type class net.minecraft.util.text.TranslationTextComponent. This is likely not what you want!
> [17:51:52] [main/WARN]: You're trying to deserialize an object of type interface net.minecraft.util.text.ITextComponent from one of type class net.minecraft.util.text.TranslationTextComponent. This is likely not what you want!
> [17:51:52] [main/WARN]: You're trying to deserialize an object of type interface net.minecraft.util.text.ITextComponent from one of type class net.minecraft.util.text.TranslationTextComponent. This is likely not what you want!

</details>

The last 6 lines repeat approximately 200 times.

**Comment by Ahcknus** [comment] 2022-05-24 01:03
Alrighty, thanks for the info, I'll probably just use the mod in a different pack cause it seems to only be an issue I've experienced with this one in particular

**Comment by StygianNights** [comment] 2022-05-24 01:06
Leave it open for now. I might look into this Wednesday when I have more free time to see what mod in particular is causing it, so we can fix it for future versions.

**Comment by Aizistral** [comment] 2022-05-30 21:52
> I might look into this Wednesday when I have more free time

So, how your looking into goes?

**Comment by Aizistral** [comment] 2022-11-08 09:19
Since looking into did not happen I'll close it back.

**Closed as completed by Aizistral** 2022-11-08 09:19 UTC
Labels: bug, 3rd party issue
