### ISSUE TITLE
[1.14.4] Crash on world creation

### ISSUE THREAD

**Issue by AK9Official** [Extegral/Enigmatic-Legacy#3] opened 2019-09-06 19:21 UTC
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 1.1.0
 * Curios API: 0.24
 * Forge: 28.0.93

#### Description of a Bug:
Can't create world with ONLY Enigmatic Legacy and Curious API... Gets stuck on 100%

#### How to Reproduce:
1. Install Curious API & Enigmatic Legacy
2. Start
3. Create world and watch it stuck itself at 100% and crash...
...
n. Behold!

#### Logs:

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).
https://paste.gg/p/anonymous/36c4d7aaa6c141f290321138115255e3

**Comment by Extegral** [comment] 2019-09-06 22:04
This issue is caused by method that is used to get persistent entity NBT, since it was renamed in latest versions of Forge.
Will be fixed in next mod's update.

**Closed** 2019-09-12 02:11 UTC
Labels: bug, crash
