### ISSUE TITLE
Game crashes due to Architect's favour and Etherium armour

### ISSUE THREAD

**Issue by callfromvoid** [Extegral/Enigmatic-Legacy#332] opened 2022-05-24 02:37 UTC
Version
 * Enigmatic Legacy: 2.21.1
 * Curios API: 5.0.7.0
 * Patchouli: 1.18.2-67
 * Forge: 40.1.23

 Description of a Bug:
If you create a world and put on a full set of Etherium armour and Architect's Favour, the game crashes

 How to Reproduce:
1. Create a world with the Creative Mode.
2. Take the Architect's Favour and the Etherium Armour.
3. Put them on.
4. Behold!

Crash report
https://www.toptal.com/developers/hastebin/otosoganig.properties

**Comment by StygianNights** [comment] 2022-05-25 17:40
I was not able to reproduce this particular issue. I checked the helpful crash report (thank you) and noticed a couple things

- You are on the list of architects favored, so that wouldn't cause it
- the error is a rendering issue, which is odd
- lots of mentions of the shield aura

So the best I can come up with, is somehow, a very obscure interaction with the Etherium armor, the Shield, or somehow something with a java version issue...? I cede this one to Aizistral.

**Comment by Aizistral** [comment] 2022-06-01 21:31
Hopefully fixed in https://github.com/Aizistral-Studios/Enigmatic-Legacy/commit/da1296129888218d11faaac59770cd56d8a644dd. Reopen the issue if you encounter it again in new update.

**Closed as completed by Aizistral** 2022-06-01 21:31 UTC
Labels: bug, crash, status: resolved
