### ISSUE TITLE
Apotheosis' crescendo of bolts enchantment (crossbow) breaks when applied alongside Enigmatic's crossbow enchantments

### ISSUE THREAD

**Issue by Graxum** [Extegral/Enigmatic-Legacy#377] opened 2022-07-27 15:40 UTC
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.24.1
 * Curios API: 1.18.2 - 5.0.7.1
 * Patchouli: 1.18.2 - 71.1
 * Forge: 40.1.60

#### Description of a Bug:
The crescendo of bolts enchantment from Apotheosis (ver.1.18.2 - 5.3.6 is used) breaks when put on a crossbow with Ceaseless and/or Sharpshooter. The crescendo of bolts enchantment is supposed to fire multiple arrows when holding down right click after loading (amount of arrows allowed to rapid-fire is proportional to the level of the enchant), however it doesn't do that when Ceaseless and/or Sharpshooter are on the crossbow.

https://user-images.githubusercontent.com/106605348/181289643-86a2c2ac-62b4-4023-8088-e60a6db08258.mp4

I also reported this issue on Apotheosis' github albeit with less detail. The bug does indeed keep happening with only those two mods and the required dependencies installed.

#### How to Reproduce:

1- put sharpshooter and/or ceaseless on a crossbow alongside Apotheosis' Crescendo of bolts enchantment. Optionally test how crescendo of bolts works on its own to get a better understanding
2- After loading the crossbow with the bugged enchantments together, try using it. You'll notice it only fires single-shots when crescendo is supposed to allow it to fire multiple without reloading.

**Comment by Aizistral** [comment] 2022-11-08 09:17
Duplicate of #124.

**Closed as completed by Aizistral** 2022-11-08 09:17 UTC
Labels: bug, duplicate
